Add Markdown for banner description and warning
bannergress/website pull request #366
Opened 2024-04-02 15:55 UTC by simbabque

This PR adds Markdown support for both the banner description and banner warning. I've put a bit of detail into #310 already. Here's a summary.

We use [react-markdown](https://github.com/remarkjs/react-markdown), which seems to be the most popular choice in the React ecosystem for rendering markdown. It offers XSS protection and can be extended, should we want it.

We only allow basic formatting in Markdown:
- paragraphs
- strong and emphasis,
- ordered and unordered lists

I've opted not to support links and images. I think images are too disruptive for the flow of the website. I think we should discuss whether we want links to be allowed. It's possible at the moment to put URLs in, but they would just not be turned into a clickable link.

Markup that is not allowed will be removed, leading to images and headings being stripped out completely.

I've also added a tooltip to the banner creation screen that includes a short explanation of what's allowed. This is available in all three languages, with the Spanish provided by a native speaker from Argentina.

I've also fixed a console error I noticed for the banner editing buttons on the banner screen.

The banner `london-skyline-830f` in the test environment has example data for this to be tried out.

Here's a screen recording of it working on the desktop site.

![Screen Recording](https://github.com/bannergress/website/assets/1125067/24e58c66-7c32-45f8-86b5-c72b1b401dc5)

Closes #310.

2024-04-04 20:22 UTC, ewoerner requested changes
Thank you for the PR. Looking quite good, but please have a look at the two comments.

2024-04-04 20:22 UTC, ewoerner commented on src/components/banner-edit-tools/BannerEditTools.tsx
These changes look unrelated. Please extract them to a separate PR.

2024-04-05 08:23 UTC, simbabque commented on src/components/banner-edit-tools/BannerEditTools.tsx
They're in PR #370 now.

2024-04-07 08:21 UTC, ewoerner approved these changes

2024-04-07 08:21 UTC, merged