fix(issue/389): update link color on faq page
bannergress/website pull request #421
Opened 2024-10-18 15:08 UTC by EinfachAleks

Close https://github.com/bannergress/website/issues/389

2024-10-23 20:10 UTC, ewoerner requested changes

2024-10-23 20:10 UTC, ewoerner commented on src/components/faq-question/faq-question.less
>    .faq-question-answer {
The issue is applies to all links, not only to the links on the FAQ page.

2024-10-25 16:06 UTC, EinfachAleks commented
@ewoerner & @KirDE code update is done, please for approve.

2024-11-01 11:00 UTC, KirDE commented
![image](https://github.com/user-attachments/assets/2da2b88d-24e2-4372-aa3b-dd4049bb838f)
on hover liks turns blue. as well as in the banner card and in FAQ.

2024-11-01 11:01 UTC, KirDE requested changes
Hover is blue

2024-11-05 21:06 UTC, EinfachAleks commented
@KirDE check it again please

2024-11-10 00:26 UTC, KirDE commented
@EinfachAleks New banner banner width slider is blue
![image](https://github.com/user-attachments/assets/509d15d0-b1aa-4754-b597-83bebef48708)

2025-06-01 21:20 UTC, EinfachAleks commented
@KirDE do it again :)

2026-08-20 21:44 UTC, KirDE approved these changes

2026-08-20 21:45 UTC, merged